name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        echo "Installing npm dependencies for custom theme..."
        npm install
        echo "Dependencies installed successfully!"

    - name: Build CSS with Tailwind
      run: |
        echo "Building Tailwind CSS..."
        npm run build:generate
        echo "CSS build completed!"

    - name: Build Hugo site
      run: |
        echo "Building Hugo site..."
        hugo --minify --cleanDestinationDir
        echo "Hugo build completed!"
        echo "Checking public directory contents:"
        ls -la public/
        echo "Checking if index.html exists:"
        ls -la public/index.html || echo "index.html not found"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: BUPTMMLab/BUPTMMLab.github.io
        publish_branch: main
        publish_dir: ./public
        user_name: 'BUPTMMLab'
        user_email: 'BUPTMMLab@gmail.com'
        commit_message: 'Deploy site from SourceBUPTMMLab at ${{ github.sha }}'
        force_orphan: true
        cname: false
